[package]
name = "enum_values"
version = "0.1.0"
authors = ["Leah <me@hrmny.sh>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1"
proc-macro-error = "1"

[dependencies.syn]
version = "1"
features = [ "default", "full", "extra-traits" ]
